/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    About: typeof import('./components/About/About.vue')['default']
    AboutAbout: typeof import('./components/About/About.vue')['default']
    Card: typeof import('./components/Featured/Card.vue')['default']
    CardList: typeof import('./components/Featured/CardList.vue')['default']
    ClientList: typeof import('./components/ClientList/ClientList.vue')['default']
    ClientListClientList: typeof import('./components/ClientList/ClientList.vue')['default']
    Controls: typeof import('./components/Particles/Controls.vue')['default']
    ControlsToggle: typeof import('./components/Particles/ControlsToggle.vue')['default']
    FeaturedCard: typeof import('./components/Featured/Card/Card.vue')['default']
    FeaturedCardList: typeof import('./components/Featured/CardList/CardList.vue')['default']
    Footer: typeof import('./components/Footer/Footer.vue')['default']
    FooterFooter: typeof import('./components/Footer/Footer.vue')['default']
    Hero: typeof import('./components/Hero/Hero.vue')['default']
    HeroHero: typeof import('./components/Hero/Hero.vue')['default']
    InputButton: typeof import('./components/Input/InputButton.vue')['default']
    InputInputButton: typeof import('./components/Input/InputButton.vue')['default']
    Logo: typeof import('./components/Logo/Logo.vue')['default']
    LogoLogo: typeof import('./components/Logo/Logo.vue')['default']
    Particles: typeof import('./components/Particles/Particles.vue')['default']
    ParticlesControls: typeof import('./components/Particles/Controls.vue')['default']
    ParticlesControlsToggle: typeof import('./components/Particles/ControlsToggle.vue')['default']
    ParticlesParticles: typeof import('./components/Particles/Particles.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Section: typeof import('./components/Section/Section.vue')['default']
    SectionSection: typeof import('./components/Section/Section.vue')['default']
    SiteContainer: typeof import('./components/SiteContainer/SiteContainer.vue')['default']
    SiteContainerSiteContainer: typeof import('./components/SiteContainer/SiteContainer.vue')['default']
  }
}
